### ISSUE TITLE
Issue when visualizing the output SVG

### ISSUE THREAD

**Issue by nmendozam** [IGBB/quack#16]
Hi,
I have been trying to use this program, but I have some trouble to find how to visualize the output.
I have used the below line, and effectively I get an output :
```
quack -1 B-LFC1.fq.gz -2 B-LFC2.fq.gz -a Sequencing_adaptors.fasta.gz > B-LFC.svg
```
But when I try to visualize it i get something like this:
![A](https://user-images.githubusercontent.com/58706237/80890875-e80e1f00-8c85-11ea-90f3-efd4cb4e03fb.png)
I know is wrong because when I try to open it in Inkscape, I see the following sort of disassembled image:
![imagen](https://user-images.githubusercontent.com/58706237/80890940-581ca500-8c86-11ea-98bd-597435e2794a.png)

Or perhaps is it an issue in the input data rather than the output?

**Comment by maa146** [comment]
Could you send the svg please? Also, do you know if the phred64 encoding the tool guessed is correct. I believe I've found the issue (a bug in our code), but I want to verify.

The second image is a known issue between the svg renderer used by Inkscape and the transformations used in the image. Unfortunately, there's not a simple fix.

**Comment by nmendozam** [comment]
Fastqc says the encoding is Illumina 1.5,  I don't know if that is what you refer by phred64, if not please tell how to find out the encoding, and I will gladly do it.
This is the link to the SVG:
https://drive.google.com/file/d/1eyJVhUKD4361PgLpCiGJRGBvBI1to4ag/view?usp=sharing

**Comment by maa146** [comment]
Thanks, Illumina 1.5 is phred64. 

The new commit should fix this issue; however, we won't be able to update the binaries until next week. I'll leave the issue open until then.

**Comment by nmendozam** [comment]
I have compiled it, and it works.
Thank you.

**Comment by adamthrash** [comment]
A new release has been created, and the binaries in the repo have been updated.
